services:
  # --------
  # Me
  # --------
  Twig\Extension\StringLoaderExtension: ~
  Twig\Extensions\IntlExtension: null

  PiedWeb\CMSBundle\PiedWebCMSBundle: ~

  PiedWeb\CMSBundle\:
    autowire: true
    resource: '../../../src/*'
    exclude: '../../../src/{Repository,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  PiedWeb\CMSBundle\Controller\:
    autowire: true
    resource: '../../../src/Controller'
    tags: ['controller.service_arguments']

  PiedWeb\CMSBundle\EventListener\UserListener:
    autowire: true
    tags:
      - {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_user%',
          event: preUpdate,
        }

  piedweb.page_rendering.validator:
    class: PiedWeb\CMSBundle\Validator\Constraints\PageRenderingValidator
    arguments:
      - '%pwc.apps%'
      - '@twig'
    tags:
      - { name: validator.constraint_validator, alias: page_rendering }

  PiedWeb\CMSBundle\Twig\AppExtension:
    tags:
      - 'twig.extension'
      #- { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    autowire: true
    arguments:
      $pageClass: '%pwc.entity_page%'

  piedweb.user_create_command:
    autowire: true
    arguments:
      $userClass: '%pwc.entity_user%'
    class: PiedWeb\CMSBundle\Command\UserCreateCommand
    tags: ['console.command']

  PiedWeb\CMSBundle\Service\App:
    alias: piedweb.app

  piedweb.app:
    class: PiedWeb\CMSBundle\Service\App
    arguments:
      $host: null
      $apps: '%pwc.apps%'
    public: true

  # --------
  # Page
  # --------

  PiedWeb\CMSBundle\EventListener\PageListener:
    autowire: true
    tags:
      - {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_page%',
          event: postLoad,
        }
      - {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_page%',
          event: preRemove,
        }

  PiedWeb\CMSBundle\Repository\PageRepository:
    arguments: ['@doctrine', '%pwc.entity_page%']
    tags:
      - { name: doctrine.repository_service }

  # --------
  # Media
  # --------

  PiedWeb\CMSBundle\Service\MediaCacheGeneratorService:
    alias: piedweb.media.cache_generator

  piedweb.media.cache_generator:
    class: PiedWeb\CMSBundle\Service\MediaCacheGeneratorService
    autowire: true
    arguments:
      $projectDir: '%kernel.project_dir%'

  piedweb.media_command:
    class: PiedWeb\CMSBundle\Command\MediaCacheGeneratorCommand
    autowire: true
    arguments:
      $mediaClass: '%pwc.entity_media%'
    tags: ['console.command']

  piedweb.media_listener:
    class: PiedWeb\CMSBundle\EventListener\MediaListener
    autowire: true
    arguments:
      $projectDir: '%kernel.project_dir%'
      $rootDir: '%kernel.root_dir%'
    tags:
      - { name: kernel.event_listener, event: vich_uploader.pre_upload }
      - { name: kernel.event_listener, event: vich_uploader.post_upload }
      - {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_media%',
          event: preUpdate,
        }
      - {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_media%',
          event: preRemove,
        }
      #- { name: doctrine.orm.entity_listener, entity: PiedWeb\CMSBundle\Entity\Image, event: prePersist }

  piedweb.media_repository:
    class: PiedWeb\CMSBundle\Repository\MediaRepository
    arguments: ['@doctrine', '%pwc.entity_media%']
    tags: ['doctrine.repository_service']

  PiedWeb\CMSBundle\Repository\MediaRepository:
    arguments: ['@doctrine', '%pwc.entity_media%']
    tags: ['doctrine.repository_service']

  # --------
  # TWIG extension
  # --------

  dpolac.twig_lambda.extension:
    class: DPolac\TwigLambda\LambdaExtension
    tags: [{ name: twig.extension }]

  piedweb.twig.extension.php_function:
    class: Umpirsky\Twig\Extension\PhpFunctionExtension
    public: false
    tags:
      - { name: twig.extension }
    calls:
      - [allowFunction, ['str_rot13']]

  piedweb.twig.extension.render_attributes:
    class: PiedWeb\RenderAttributes\TwigExtension
    public: false
    tags:
      - { name: twig.extension }

  # --------
  # Extending other bundles
  # --------

  # Liip
  # --------

  piedweb.media.web_path_resolver:
    class: PiedWeb\CMSBundle\Service\MediaWebPathResolver
    arguments:
      - '@filesystem'
      - '@router.request_context'
      - '%pwc.dir%'
    tags:
      - {
          name: 'liip_imagine.cache.resolver',
          resolver: piedweb_media_webpath_resolver,
        }

  # Vich
  # --------

  vich_uploader.piedweb.namer_property:
    class: PiedWeb\CMSBundle\Service\VichUploadPropertyNamer
    public: true
    arguments: ['@Vich\UploaderBundle\Util\Transliterator']

  PiedWeb\CMSBundle\Service\VichUploadPropertyNamer:
    alias: vich_uploader.piedweb.namer_property
    public: true
