piedweb_cms_page_sitemap:
  path: /{_locale}sitemap.{_format}
  controller: PiedWeb\CMSBundle\Controller\PageController::showSitemap
  methods: [GET, HEAD]
  requirements:
    _locale: '[a-zA-Z]{2}(_[a-zA-Z]+)?\/|'
    _format: 'xml|txt'

piedweb_cms_page_main_feed:
  path: /{_locale}feed.xml
  controller: PiedWeb\CMSBundle\Controller\PageController::showMainFeed
  methods: [GET, HEAD]
  requirements:
    _locale: '[a-zA-Z]{2}(_[a-zA-Z]+)?\/|'

piedweb_cms_page_feed:
  path: /{slug}.xml
  controller: PiedWeb\CMSBundle\Controller\PageController::showFeed
  methods: [GET, HEAD]
  requirements:
    slug: '[a-zA-Z0-9\-/]*'
# todo : add priority to this route https://symfony.com/doc/current/routing.html#priority-parameter
# move routes to annotation ?!
# permit to use extension without bug with this catch all
