page_routes:
  resource: '@PiedWebCMSBundle/Resources/config/routes/page.yaml'

custom_host_routes:
  resource: '@PiedWebCMSBundle/Resources/config/routes/page.yaml'
  prefix: '/{host}/'
  name_prefix: 'custom_host_'
  requirements:
    host: '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
    #'[a-zA-Z0-9\-\.]*'

## Catch-all

custom_host_piedweb_cms_page:
  path: /{host}/{slug}
  controller: PiedWeb\CMSBundle\Controller\PageController::show
  methods: [GET, HEAD]
  requirements:
    slug: '[a-zA-Z0-9\-/]*'
    host: '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'

piedweb_cms_page:
  path: /{slug}
  controller: PiedWeb\CMSBundle\Controller\PageController::show
  methods: [GET, HEAD]
  requirements:
    slug: '[a-zA-Z0-9\-/]*'
