sonata_admin:
  security:
    handler: sonata.admin.security.handler.role
    role_admin: ROLE_ADMIN
    role_super_admin: ROLE_SUPER_ADMIN
  title: 'Admin'
  title_logo: assets/logo_title.png
  dashboard:
    blocks:
    #- { type: sonata.admin.block.admin_list, position: left }
    groups:
      app.admin.group.page:
        label: admin.label.content
        label_catalogue: messages
        items:
          - piedweb.admin.page
          - piedweb.admin.media
          - piedweb.admin.conversation
      app.admin.group.static:
        label: admin.label.manage
        label_catalogue: messages
        icon: '<i class="fa fa-bolt"></i>'
        items:
          - route: piedweb_cms_page_scanner
            label: admin.label.check_content
          - route: piedweb_static_generate
            label: admin.label.update

      app.admin.group.setting:
        label: admin.label.params
        label_catalogue: messages
        icon: '<i class="fa fa-wrench"></i>'
        items:
          - piedweb.admin.user
          - route: piedweb_cms_template_editor_list
            label: admin.label.theme
  options:
    lock_protection: true
  assets:
    extra_stylesheets:
      - bundles/sonatatranslation/css/sonata-translation.css

sonata_doctrine_orm_admin:
  templates:
    form:
      - '@PiedWebCMS/admin/Form/sd_form_admin_fields.html.twig'

sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]

    sonata.admin.block.search_result:
      contexts: [admin]
