imports:
  - { resource: '../../../src/Resources/config/services/all.yaml' }
  - { resource: '../../../src/Extension/Admin/AdminServices.yaml' }
  - { resource: '../../../src/Extension/StaticGenerator/StaticServices.yaml' }
  - { resource: '../../../src/Extension/PageScanner/PageScannerServices.yaml' }
  - { resource: '../../../src/Extension/Router/RouterServices.yaml' }
  - { resource: '../../../src/Extension/PageMainContentManager/PMCMServices.yaml' }
  - { resource: '../../../src/Extension/UpdateNotification/UpdateNotificationServices.yaml' }
