services:
  # --------
  # Me
  # --------
  Twig\Extension\StringLoaderExtension: ~

  twig.extension.stringloader:
    class: Twig_Extension_StringLoader
    tags:
      - { name: twig.extension }

  PiedWeb\CMSBundle\PiedWebCMSBundle: ~

  PiedWeb\CMSBundle\:
    autowire: true
    resource: '../../../src/*'
    exclude: '../../../src/{Repository,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  PiedWeb\CMSBundle\Controller\:
    autowire: true
    resource: '../../../src/Controller'
    tags: ['controller.service_arguments']

  PiedWeb\CMSBundle\EventListener\MediaListener:
    arguments:
      $projectDir: '%kernel.project_dir%'
      $em: '@doctrine.orm.entity_manager'
      $cacheManager: '@liip_imagine.cache.manager'
      $dataManager: '@liip_imagine.data.manager'
      $filterManager: '@liip_imagine.filter.manager'
      $eventDispatcher: '@event_dispatcher'
    tags:
      - { name: kernel.event_listener, event: vich_uploader.pre_upload }
      - { name: kernel.event_listener, event: vich_uploader.post_upload }
      #- { name: doctrine.orm.entity_listener, entity: PiedWeb\CMSBundle\Entity\Image, event: prePersist }

  PiedWeb\CMSBundle\EventListener\PageListener:
    tags:
      - {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_page%',
          event: preRemove,
        }

  piedweb.pageUpdate.emailNotifier:
    class: PiedWeb\CMSBundle\Service\PageUpdateMailNotifier
    arguments:
      [
        '%pwc.entity_page%',
        '@mailer',
        '%pwc.email_sender%',
        '%pwc.page_update_notification_email%',
        '%pwc.name%',
        '%kernel.root_dir%',
        '%pwc.page_update_notification_interval%',
        '@doctrine.orm.entity_manager',
        '@translator',
      ]
    tags:
      [
        {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_page%',
          event: postUpdate,
        },
        {
          name: doctrine.orm.entity_listener,
          entity: '%pwc.entity_page%',
          event: postPersist,
        },
      ]

  PiedWeb\CMSBundle\Service\PageScannerService:
    class: PiedWeb\CMSBundle\Service\PageScannerService
    arguments:
      ['@twig', '@doctrine.orm.entity_manager', '%pwc.dir%', '%pwc.apps%']

  piedweb.page_rendering.validator:
    class: PiedWeb\CMSBundle\Validator\Constraints\PageRenderingValidator
    arguments:
      - '%pwc.apps%'
      - '@twig'
    tags:
      - { name: validator.constraint_validator, alias: page_rendering }

  PiedWeb\CMSBundle\Twig\AppExtension:
    tags:
      - 'twig.extension'
      #- { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    arguments:
      [
        '@doctrine.orm.entity_manager',
        '%pwc.entity_page%',
        '@piedweb.page_canonical',
      ]

  piedweb.page_canonical:
    class: PiedWeb\CMSBundle\Service\PageCanonicalService
    arguments:
      [
        '@request_stack',
        '@router',
        '%pwc.default_locale_without_prefix%',
        '%locale%',
      ]
    public: true

  PiedWeb\CMSBundle\Service\PageCanonicalService:
    alias: piedweb.page_canonical
    public: true

  piedweb.media_command:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@parameter_bag'
      - '@liip_imagine.cache.manager'
      - '@liip_imagine.data.manager'
      - '@liip_imagine.filter.manager'
      - '%pwc.dir%'
    class: PiedWeb\CMSBundle\Command\MediaCommand
    tags: ['console.command']

  # --------
  # Static
  # --------

  piedweb.static:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@twig'
      - '@parameter_bag'
      - '@request_stack'
      - '@piedweb.page_canonical'
      - '@translator'
      - '%pwc.dir%'
    class: PiedWeb\CMSBundle\Service\StaticService

  PiedWeb\CMSBundle\Service\StaticService:
    alias: piedweb.static

  piedweb.static_controller:
    arguments: ['@piedweb.static']
    class: PiedWeb\CMSBundle\Controller\StaticController
    tags: ['controller.service_arguments']

  piedweb.static_command:
    arguments: ['@piedweb.static']
    class: PiedWeb\CMSBundle\Command\StaticCommand
    tags: ['console.command']

  # --------
  # Repository
  # --------

  PiedWeb\CMSBundle\Repository\PageRepository:
    arguments: ['@doctrine', '%pwc.entity_page%']
    tags:
      - { name: doctrine.repository_service }

  PiedWeb\CMSBundle\Repository\MediaRepository:
    arguments: ['@doctrine', '%pwc.entity_media%']
    tags:
      - { name: doctrine.repository_service }

  # --------
  # Admin
  # --------

  piedweb.admin.page:
    class: PiedWeb\CMSBundle\Admin\PageAdmin
    arguments:
      - ~
      - '%pwc.entity_page%'
      - PiedWeb\CMSBundle\Controller\PageAdminController
    tags:
      - { name: sonata.admin, manager_type: orm, label: admin.label.page }
    calls:
      - [setLiipImage, ['@liip_imagine.cache.manager']]
      - [setTemplate, [list, '@@PiedWebCMS/admin/media_mosaic.html.twig']]
      - [setTemplate, [show, '@@PiedWebCMS/admin/page_show.html.twig']]
      - [setTemplate, [edit, '@@PiedWebCMS/admin/page_edit.html.twig']]
      - [setDefaultLocale, ['%locale%']]
    public: true

  piedweb.admin.media:
    class: PiedWeb\CMSBundle\Admin\MediaAdmin
    arguments: [~, '%pwc.entity_media%', ~]
    calls:
      - [setLiipImage, ['@liip_imagine.cache.manager']]
      - [setTemplate, [list, '@@PiedWebCMS/admin/media_mosaic.html.twig']]
    tags:
      - { name: sonata.admin, manager_type: orm, label: admin.label.media }

  piedweb.admin.pagehasmedia:
    class: PiedWeb\CMSBundle\Admin\PageHasMedia
    arguments: [~, '%pwc.entity_pagehasmedia%', ~]
    calls:
      - [setLiipImage, ['@liip_imagine.cache.manager']]
    tags:
      - { name: sonata.admin, manager_type: orm }

  piedweb.admin.user:
    class: PiedWeb\CMSBundle\Admin\UserAdmin
    arguments: [~, '%pwc.entity_user%', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: admin.label.user }
    public: true

  # --------
  # TWIG extension
  # --------

  dpolac.twig_lambda.extension:
    class: DPolac\TwigLambda\LambdaExtension
    tags: [{ name: twig.extension }]

  piedweb.twig.extension.php_function:
    class: Umpirsky\Twig\Extension\PhpFunctionExtension
    public: false
    tags:
      - { name: twig.extension }
    calls:
      - [allowFunction, ['str_rot13']]

  piedweb.twig.extension.render_attributes:
    class: PiedWeb\RenderAttributes\TwigExtension
    public: false
    tags:
      - { name: twig.extension }

  # --------
  # Extending other bundles
  # --------

  imagine.cache.resolver.piedweb:
    class: PiedWeb\CMSBundle\Service\ImagineWebCacheResolver
    arguments:
      - '@filesystem'
      - '@router.request_context'
      - '%pwc.dir%'
    tags:
      - {
          name: 'liip_imagine.cache.resolver',
          resolver: piedweb_relativeimgcache,
        }

  vich_uploader.piedweb.namer_property:
    class: PiedWeb\CMSBundle\Service\VichUploadPropertyNamer
    public: true
    arguments: ['@Vich\UploaderBundle\Util\Transliterator']

  PiedWeb\CMSBundle\Service\VichUploadPropertyNamer:
    alias: vich_uploader.piedweb.namer_property
    public: true
