imports:
  - { resource: '../../../src/Resources/config/services/all.yaml' }
  - { resource: '../../../src/Admin/AdminServices.yaml' }
  - { resource: '../../../src/StaticGenerator/StaticServices.yaml' }
