piedweb_cms_admin_dashboard:
  path: /admin/dashboard
  controller: Sonata\AdminBundle\Controller\CRUDController::listAction
  defaults:
    _sonata_admin: piedweb.admin.page

admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

piedweb_cms_markdown_cheatsheet:
  path: /admin/markdown-cheatsheet
  methods: [GET, HEAD]
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: '@pwcAdmin/markdown_cheatsheet.html.twig'
