#used for tests

piedweb_cms:
  locale: '%locale%'
  entity_page: App\Entity\Page
  entity_pagehasmedia: App\Entity\PageHasMedia
  entity_media: App\Entity\Media
  entity_user: App\Entity\User
  apps:
    - {
        hosts: ['localhost.dev', 'localhost'],
        base_url: 'https://localhost.dev',
      }
# locale
# locales
# hosts:
# base_url:                 // defaut https://%host%
# name                      // used in UpdateNotificationService and in Conversation
# main_content_type
# template                  // default template

# customProperties (json) variableNode
#   main_content_shortcode    video,image,mail,phone,date // wich shortcode can be used ?
#   field_shortcode           date
#   main_content_twig         // can use twig ?

#   static_dir
#   static_generateFor      // Apache/GithubPages

#   page_update_notification_mail
#   page_update_notification_interval

#   notifier_email
#   notifier_email_name
#   color
